# Generated by Django 5.2 on 2025-04-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180620_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Rape_Cases_Reported',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Victims_Above_50_Yrs',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Victims_Between_10to14_Yrs',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Victims_Between_14to18_Yrs',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Victims_Between_18to30_Yrs',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Victims_Between_30to50_Yrs',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Victims_Upto_10_Yrs',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Victims_of_Rape_Total',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='murder',
            name='Victims_Above_50_Yrs',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='murder',
            name='Victims_Total',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='murder',
            name='Victims_Upto_10_15_Yrs',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='murder',
            name='Victims_Upto_10_Yrs',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='murder',
            name='Victims_Upto_15_18_Yrs',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='murder',
            name='Victims_Upto_18_30_Yrs',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='murder',
            name='Victims_Upto_30_50_Yrs',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
